name: 'Sync README to Notion'
description: 'A GitHub Action to sync README.md to a Notion page'
author: 'Christian Möller'
inputs:
  notion_token:
    description: 'Notion integration token'
    required: true
  notion_page_id:
    description: 'Notion page ID'
    required: true
outputs:
  success:
    description: 'Indicates if the sync was successful'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Run main script
      run: node update-notion.js
      shell: bash